CI: restore arm64 conda tests, re-use run_* scripts in test_* scripts (#429)
Splitting some changes off of #425

* re-enable arm64 conda tests
* adding a small test with `torch.cuda.is_available()` in conda CI tests
* updates `ci/test_*` scripts to re-use `ci/run_*` scripts

## Notes for Reviewers

### How I tested this

Ran the full PR and nightly matrices of `conda-python-tests` here.

https://github.com/rapidsai/cugraph-gnn/actions/runs/22935844055/job/66568277622?pr=429

All except arm64 + CUDA 12.2 passed (that combination doesn't have `pytorch` conda packages), so added matrix filters skipping that one combination: https://github.com/rapidsai/cugraph-gnn/pull/429#discussion_r2915692197

### How can we enable arm tests now?

Since they were originally filtered out, `pytorch` packages with GPU support have made it to `conda-forge`.

So the reasoning that there aren't available packages (https://github.com/rapidsai/cugraph-gnn/issues/167#issuecomment-2770514968) no longer holds.

We should now be able to test on arm64 😁 

### Why add this import test?

`torch` is an optional dependency of both `cugraph-pyg` and `pylibwholegraph`. The things done to keep it optional introduce risk of it accidentally not being installed in CI, or a CPU-only version of it being installed.

Right now, when that happens you're confronted with a hard-to-understand error like

```text
E   AttributeError: module 'torch._C' has no attribute '_cuda_changeCurrentAllocator'
```

Hopefully we never accidentally install CPU-only `torch` in CI again, but if it does happen the test introduced in this PR should save some debugging time.

### Why re-use the `run_*` scripts from `test_*` scripts?

Reduces duplication.

And more importantly, ensures this project's tests are runnable in DLFW builds (where only the `run_*` scripts are used because they are not tightly coupled to RAPIDS CI setup).

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - Alex Barghi (https://github.com/alexbarghi-nv)

URL: https://github.com/rapidsai/cugraph-gnn/pull/429